name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  tests:
    runs-on: macOS-11.0
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode 12.2
        run: sudo xcode-select -s /Applications/Xcode_12.2.app
      - name: Run tests
        run: make test
      - name: Select Xcode 12
        run: sudo xcode-select -s /Applications/Xcode_12.app
      - name: Run snapshot tests
        run: make snapshot-test-ios      
