name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  tests:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode 12
        run: sudo xcode-select -s /Applications/Xcode_12.app
      - name: Run tests
        run: make test
